### ISSUE TITLE
Error when trying to get user info with token

### ISSUE THREAD

**Issue by AndyWendt** [SocialiteProviders/Trello#1]
The error is: 

```
Exception in Server.php line 244: Received error [invalid token
] with status code [400] when retrieving token credentials.
```

Because the `token` query param is null: `https://trello.com/1/members/me?key=<the_key>&token=`

It looks like setting the access token is different for Trello: [trello server](https://github.com/thephpleague/oauth1-client/blob/master/src/Client/Server/Trello.php#L62) ::setAccessToken($accessToken)

**Comment by DraperStudio** [comment]
Thanks.
