### ISSUE TITLE
Can't set the expiration or the app name

### ISSUE THREAD

**Issue by stulogy** [SocialiteProviders/Trello#3]
It might just be lack of documentation, but I cannot seem to work out how to set the expiration parameter or the app name. 

My code is simply: 

`return Socialite::driver('trello')->redirect();` 

But adding `->with(['expiration' => 'never'])` doesn't work, it just throws an exception.

**Comment by DraperStudio** [comment]
Is that something for Authentication process to get an access token or after you have received an access token?

**Comment by stulogy** [comment]
It’s to get an access token. You can’t set the parameters of the token, e.g. you can’t say how long you want the token to last and you can’t set the app name or anything like that, which makes it pretty useless. I had to build my own Service Provider.

**Comment by DraperStudio** [comment]
Then please post the exception you get, without it I can't do much.

**Comment by stulogy** [comment]
I don’t have an exception, I just can’t pass any parameter to set the name, expiration and the scope.

I ended up using `League\OAuth1\Client\Server\Trello` and creating my own class to authenticate, as I couldn’t use Socialite.

I need to be able to pass these parameters with the with() method, but I can’t write now:

    ->with([
        'scope' => 'read,write',
        'expiration' => 'never',
        'name' => ‘HourStack
    ])

**Comment by DraperStudio** [comment]
This seems to be an issue with Socialite itself because it has no with-method for OAuth1 Providers.

Will look into this soon.

**Comment by DraperStudio** [comment]
We now added support for the **with** and **scopes** method for OAuth1 Providers.

I tested the Trello Provider now with the following setup and everything was working as it is supposed to.

```
Route::get('/trello', function (Request $request) {
    return Socialite::driver('trello')->with([
        'expiration' => 'never',
        'name' => 'HourStack'
    ])->scopes(['read', 'write'])->redirect();
});

Route::get('/trellocb', function (Request $request) {
    $user = Socialite::driver('trello')->user();

    dd($user);
});
```

**Comment by stulogy** [comment]
Wow – fast! Thank you.

**Comment by DraperStudio** [comment]
I have released v2.0.2 which now uses the **mapUserToObject** method like the OAuth2 Providers which will Provide much cleaner code.

I will close this for now, if you still have any issues re-open this.

**Comment by AndyWendt** [comment]
@stulogy @DraperStudio is fast :smile:

**Comment by stulogy** [comment]
Just got this installed. The redirect works now beautifully, thank you. 

However the handle response doesn't work. 

My code is simply:

`        $user = Socialite::driver('trello')->user();
`       dd($user);

I'm getting:

ErrorException in AbstractProvider.php line 94:
Undefined index: oauth_temp

**Comment by DraperStudio** [comment]
There seems to be an issue with your session. If I remember correctly I got the `oauth_temp` error when i had session disabled.

**Comment by DraperStudio** [comment]
This is the part where we need to store the `oauth_temp` as cookie if a provider is configured to be stateless.

https://github.com/SocialiteProviders/Manager/blob/5285e596195c437c66a6c6c4f8605ab13d418964/src/OAuth1/AbstractProvider.php#L61-L100

**Comment by stulogy** [comment]
Yes I can understand this, but I'm not sure why it would be happening. My redirect route and the callback route are inside the 'web' group so sessions are enabled. I have DB sessions enabled (not stateless).

**Comment by stulogy** [comment]
I did some debugging, and I set `protected $stateless` to `false` and that fixed the issue. The cookie is being deleted for some reason, and that is why this is happening. I'm not sure what a perminant solution for this would be?
